Repository Pudin-con-pasas-uwu/AdminPage, pull requests merged in 2023-03, with the labels that each got.

#2 tabla de productos
  src/components/ProductsModule/ButtomBak.jsx
  src/components/ProductsModule/ButtomProductsTable.jsx
  src/components/ProductsModule/ProductsTable.jsx
  src/components/ProductsModule/ProductsTableEdit.jsx
  src/components/ProductsModule/SearchBarProductos.jsx
  src/components/componentsDetaillProducts/descriptionProducts.jsx
  src/components/componentsDetaillProducts/imgProducts.jsx
  src/img/Ejemplo.jpg
  src/img/logo.jpg
  src/img/logo.png
  src/img/placer 2.jpg
  src/img/placer3.jpg
  src/pages/ProductsModule.js
  src/pages/ProductsModule/ProductsAdd/ModuleProductsAdd.js
  src/pages/ProductsModule/ProductsEdit/[id].js
  src/pages/ProductsModule/[id].js
  src/pages/api/hello.js
  src/styles/ProductsTable.module.css
  src/styles/SearchBarProducts.module.css
  src/styles/butomSelectProducts.module.css
  src/styles/globals.css
Labels: enhancement, good first issue

#10 Código Log In
  next-env.d.ts
  package-lock.json
  package.json
  src/components/LoginPage.jsx
  src/components/Navpage.jsx
  src/components/ProductsModule/ProductsTable.jsx
  src/components/ProductsModule/SearchBarProductos.jsx
  src/imgs/logo.jpg
  src/pages/Categorias.js
  src/pages/ProductsModule.js
  src/pages/ProductsModule/ProductsAdd/ModuleProductsAdd.js
  src/pages/ProductsModule/ProductsEdit/[id].js
  src/pages/ProductsModule/[id].js
  src/pages/Roles.js
  src/pages/Users.js
  src/pages/_app.js
  src/pages/api/hello.js
  src/pages/index.js
  src/styles/globals.css
  src/styles/login.module.css
  tsconfig.json
Labels: bug, duplicate

#11 OrdersFinal
  src/components/Navpage.jsx
  src/components/OrdersMod.jsx
  src/pages/_app.js
  src/pages/orders.js
  src/styles/OrdersMod.css
Labels: duplicate, enhancement

#13 Creación de Responsive
  src/components/LoginPage.jsx
  src/styles/login.module.css
Labels: documentation

#17 Validación Login
  src/components/LoginPage.jsx
  src/styles/login.module.css
Labels: documentation, enhancement, help wanted

#19 redireccionamiento arreglado
  src/components/ProductsModule/ButtomBak.jsx
  src/components/ProductsModule/ButtomProductsTable.jsx
  src/components/ProductsModule/ProductsTable.jsx
  src/components/ProductsModule/ProductsTableEdit.jsx
  src/components/ProductsModule/SearchBarProductos.jsx
  src/pages/ProductsModule/ProductsAdd/ModuleProductsAdd.js
  src/pages/ProductsModule/ProductsEdit/[id].js
  src/pages/ProductsModule/[id].js
  src/styles/SearchBarProducts.module.css
Labels: documentation, duplicate

#21 importaciones con @
  jsconfig.json
  next-env.d.ts
  src/components/Layouts/awdawdawd/rolslayout.jsx
  src/pages/Roles.js
  tsconfig.json
Labels: bug, enhancement

#24 ValidaciónLgI
  src/components/LoginPage.jsx
  src/pages/Categorias.js
  src/pages/ProductsModule.js
  src/pages/Roles.js
  src/pages/Users.js
  src/pages/orders.js
  src/styles/login.module.css
Labels: documentation, duplicate, enhancement, help wanted
