Repository Pudin-con-pasas-uwu/AdminPage, pull requests merged in 2023-04, with the labels that each got.

#27 changes in the product name
  src/components/ProductsModule/ProductsTable.jsx
  src/styles/ProductsTable.module.css
Labels: enhancement

#30 Btn add en Users
  src/components/UserMod/BuscadorUser.jsx
  src/components/UserMod/FormUser.jsx
  src/components/UserMod/OrderUser.jsx
  src/components/UserMod/UsersMod.jsx
  src/pages/UsersModule/UsersADD.js
  src/styles/Users_Mod.css
Labels: enhancement

#31 LogIn (alter.)
  src/components/LoginPage.jsx
  src/pages/ProductsModule.js
Labels: bug, documentation

#33 rol & categorie module Add
  src/components/Categorias/Addingcat.jsx
  src/components/Categorias/Categories_title.jsx
  src/components/Categorias/add_header.jsx
  src/components/Roles/AddRol_header.jsx
  src/components/Roles/roleadding.jsx
  src/components/Roles/roles.jsx
  src/components/categories.jsx
  src/pages/Add_role.js
  src/pages/Categorias.js
  src/pages/Categorie_add.js
  src/styles/rol_table.css
Labels: enhancement

#34 LG-Completo
  src/components/LoginPage.jsx
  src/pages/Categorias.js
  src/pages/ProductsModule.js
  src/pages/Roles.js
  src/pages/Users.js
  src/pages/orders.js
Labels: documentation, enhancement

#35 reacondicionamiento de modulos
  src/components/Categorias/Addingcat.jsx
  src/components/Categorias/add_header.jsx
  src/components/Categorias/categories.jsx
  src/components/Roles/AddRol_header.jsx
  src/components/Roles/roleadding.jsx
  src/components/Roles/roles.jsx
  src/pages/Categorias.js
  src/pages/Categorie_add.js
  src/pages/Roles.js
  src/styles/rol_table.css
Labels: enhancement

#36 se hace cambios para que funcione el boton eliminar y el de agregar
  src/components/ProductsModule/ProductsTable.jsx
  src/components/ProductsModule/ProductsTableAdd.jsx
  src/components/ProductsModule/RegisterProducts.jsx
  src/pages/ProductsModule/ProductsAdd/ModuleProductsAdd.js
  src/pages/ProductsModule/ProductsEdit/[id].js
Labels: bug, duplicate

#39 Cambios en el ordersMod
  src/components/Layouts/Layout.jsx
  src/components/Navpage.jsx
  src/components/Orders/OrderDetail.jsx
  src/components/Orders/OrderUpdate.jsx
  src/components/Orders/OrdersMod.jsx
  src/components/OrdersMod.jsx
  src/pages/OrdersModule/order_detail/[id].js
  src/pages/OrdersModule/order_update/[id].js
  src/pages/OrdersModule/orders.js
  src/pages/_app.js
  src/pages/orders.js
  src/styles/OrdersMod.css
  src/styles/rol_table.css
Labels: enhancement

#42 Permisos/LogOut/Refresh
  src/components/LoginPage.jsx
  src/components/Navpage.jsx
  src/pages/Categorias.js
  src/pages/ProductsModule.js
  src/pages/Roles.js
  src/pages/Users.js
  src/styles/About.css
Labels: documentation, enhancement

#41 se agregaron los nombres de las categorias en la tabla de productos
  src/components/ProductsModule/ProductsTable.jsx
  src/pages/ProductsModule.js
Labels: documentation

#45 Cambio de rutas y validación de token
  src/pages/OrdersModule/order_detail/[id].js
  src/pages/OrdersModule/order_update/[id].js
  src/pages/OrdersModule/orders.js
Labels: enhancement

#48 Cambio de Endpoints
  src/components/LoginPage.jsx
  src/pages/Categorias.js
  src/pages/Categorie_add.js
  src/pages/OrdersModule/orders.js
  src/pages/ProductsModule.js
  src/pages/Roles.js
  src/pages/Users.js
Labels: documentation

#49 Cambios Ends/Login
  src/components/LoginPage.jsx
  src/pages/OrdersModule/orders.js
  src/pages/ProductsModule.js
Labels: documentation

#46 pequenos cambios
  src/components/ProductsModule/CategorySelect.jsx
  src/components/ProductsModule/ProductsTableAdd.jsx
  src/components/ProductsModule/RegisterProducts.jsx
Labels: documentation

#51 Corección OrderDetail
  src/components/Orders/OrderDetail.jsx
Labels: enhancement

#50 OrderDelete
  src/components/Orders/OrdersMod.jsx
Labels: enhancement

#47 Mejora en el formulario de orders
  src/components/Orders/FormOrders.jsx
  src/components/Orders/OrdersMod.jsx
  src/pages/OrdersModule/orderadd/OrderAdd.js
  src/styles/formord.module.css
Labels: enhancement

#54 se agregaron las imagenes a la tabla de productos y pequeños cambios en el boton edit y en el add
  public/imgs/1.jpg
  public/imgs/2.jpg
  public/imgs/3.jpg
  public/imgs/4.jpg
  public/imgs/5.jpg
  public/imgs/6.jpg
  public/imgs/7.jpg
  public/imgs/Ejemplo.jpg
  public/imgs/awdawdawd.jpg
  public/imgs/img1.jpg
  public/imgs/img2.jpg
  public/imgs/img3.jpg
  public/imgs/img4.jpg
  src/components/ProductsModule/ProductsTable.jsx
  src/components/ProductsModule/ProductsTableEdit.jsx
  src/components/ProductsModule/RegisterProducts.jsx
  src/pages/ProductsModule.js
  src/pages/ProductsModule/ProductsEdit/[id].js
  src/styles/ProductsTable.module.css
Labels: documentation

#56 Rutas protegidas
  src/pages/Add_role.js
  src/pages/Categorie_add.js
  src/pages/OrdersModule/order_detail/[id].js
  src/pages/OrdersModule/order_update/[id].js
  src/pages/OrdersModule/orderadd/OrderAdd.js
  src/pages/ProductsModule/ProductsAdd/ModuleProductsAdd.js
  src/pages/ProductsModule/ProductsEdit/[id].js
  src/pages/ProductsModule/[id].js
  src/pages/UsersModule/UsersADD.js
  src/pages/UsersModule/UsersEdit.js
  src/pages/categoriesactions/[id].js
  src/pages/roleactions/[id].js
Labels: documentation
